# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => '/storage/VM/hdd/d33.vdi',
			:size => 2048,
			:port => 1
		},
	}
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|
          
	  box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
		vb.gui = false
          	vb.customize ["modifyvm", :id, "--memory", "1024"]
#		vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ] #
		boxconfig[:disks].each do |dname, dconf|
			unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
			end
			vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
		end
          end
	  box.vm.provision "shell", path: "./SCRIPTS/init.sh"
      end
  end
end

