#!/bin/bash
# chkconfig: 23 70 20
# description: checking Keyword in a Logfile
# Source function library.
. /etc/init.d/functions
# include config
. /etc/sysconfig/mon_keyword_serviceSysV.conf

case "$1" in
start)
    # Check on existence
    if ! [ -d /var/log/mon_keyword_serviceSysV/ ]; then
	`mkdir /var/log/mon_keyword_serviceSysV`
    fi
    echo "$(date) service $0 started" >> /var/log/mon_keyword_serviceSysV/daemon.log
    /vagrant/SCRIPTS/mon_keyword_proc.sh "$Keyword" "$Logfile" "$INTERVALOFCHECK" &
    echo $!>/var/run/mon_keyword_serviceSysV.pid
    ;;
stop)
    echo "$(date) service $0 stopped" >> /var/log/mon_keyword_serviceSysV/daemon.log
    kill -15 `cat /var/run/mon_keyword_serviceSysV.pid`
    rm /var/run/mon_keyword_serviceSysV.pid
    ;;
restart)
    $0 stop
    $0 start
    ;;
status)
    if [ -e /var/run/mon_keyword_serviceSysV.pid ]
    then
        echo "mon_keyword_serviceSysV is running, pid=`cat /var/run/mon_keyword_serviceSysV.pid`"
    else
        echo "mon_keyword_serviceSysV is NOT running"
        exit 1
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0


