#!/bin/bash
# chkconfig: 23 70 20
# description: checking Keyword in a Logfile
# Source function library.
. /etc/init.d/functions
# include config
#. /etc/sysconfig/mon_keyword_serviceSysV.conf
Keyword="Started Session 12"
Logfile="/var/log/messages"

case "$1" in
start)
    echo "$(date) service $0 started" >> /vagrant/SCRIPTS/log/mon_keyword_serviceSysV.log
    /vagrant/SCRIPTS/mon_keyword_proc.sh "$Keyword" "$Logfile" /var/log/messages &
	echo "$Keyword $Logfile"
    echo $!>/vagrant/SCRIPTS/run/mon_keyword_serviceSysV.pid
    ;;
stop)
    echo "$(date) service $0 stopped" >> /vagrant/SCRIPTS/log/mon_keyword_serviceSysV.log
    kill -15 `cat /vagrant/SCRIPTS/run/mon_keyword_serviceSysV.pid`
    rm /vagrant/SCRIPTS/run/mon_keyword_serviceSysV.pid
    ;;
restart)
    $0 stop
    $0 start
    ;;
status)
    if [ -e /vagrant/SCRIPTS/run/mon_keyword_serviceSysV.pid ]
    then
        echo "mon_keyword_serviceSysV is running, pid=`cat /vagrant/SCRIPTS/run/mon_keyword_serviceSysV.pid`"
    else
        echo "mon_keyword_serviceSysV is NOT running"
        exit 1
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
    
    
